name = "LinkCutTreesAugmented"
uuid = "c1bc6fde-6912-42fb-b8df-7f936dc5be7d"
authors = ["Jonathan Mattingly <jonathan.mattingly@gmail.com>", "Gregory Herschlag <gjh@math.duke.edu>"]
version = "0.2"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
Graphs = "1"
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
